services:
  mongodb:
    image: mongo:7
    container_name: botwa-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - botwa_mongo_data:/data/db

volumes:
  botwa_mongo_data:
